#ifndef QT6ROCKCHIP_QSKELETON_GLOBAL_H
#define QT6ROCKCHIP_QSKELETON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT6ROCKCHIP_QSKELETON_LIBRARY)
#define QT6ROCKCHIP_QSKELETON_EXPORT Q_DECL_EXPORT
#else
#define QT6ROCKCHIP_QSKELETON_EXPORT Q_DECL_IMPORT
#endif

#endif // QT6ROCKCHIP_QSKELETON_GLOBAL_H

